-- Initialize users and schemas for Oracle Free 23ai (PDB: FREEPDB1)
ALTER SESSION SET CONTAINER = FREEPDB1;

-- Create user for ATP (OLTP store)
CREATE USER portfolio_atp IDENTIFIED BY devpassword DEFAULT TABLESPACE users TEMPORARY TABLESPACE temp QUOTA UNLIMITED ON users;
GRANT CONNECT, RESOURCE, DBA TO portfolio_atp;
GRANT CREATE SESSION, CREATE TABLE, CREATE VIEW, CREATE SEQUENCE, CREATE PROCEDURE, CREATE TRIGGER TO portfolio_atp;

-- Create user for ADW (Analytics star schema store)
CREATE USER portfolio_adw IDENTIFIED BY devpassword DEFAULT TABLESPACE users TEMPORARY TABLESPACE temp QUOTA UNLIMITED ON users;
GRANT CONNECT, RESOURCE, DBA TO portfolio_adw;
GRANT CREATE SESSION, CREATE TABLE, CREATE VIEW, CREATE SEQUENCE, CREATE PROCEDURE, CREATE TRIGGER TO portfolio_adw;
