-- 0001_init.up.sql — initial schema for the portfolio backend (Oracle ATP schema).
-- UUID PKs are VARCHAR2(36 CHAR) with no DB-side default: UUIDs are generated by the
-- Go service layer. Postgres enums are modeled as VARCHAR2(20) + CHECK constraints
-- (no Oracle TYPE objects). Naming: plural snake_case tables, {table}_id primary keys,
-- idx_{table}_{column} indexes.
-- NOTE: "current" is an Oracle reserved word and must stay double-quoted everywhere
-- (DDL, seed data, and any SQL emitted by the Go repository layer).

CREATE TABLE experiences (
    experience_id    VARCHAR2(36 CHAR) PRIMARY KEY,
    experience_type  VARCHAR2(20)      NOT NULL CHECK (experience_type IN ('work', 'education')),
    organization     VARCHAR2(500),
    role_title       VARCHAR2(500),
    location         VARCHAR2(500),
    start_date       DATE              NOT NULL,
    end_date         DATE,
    "current"        NUMBER(1)         DEFAULT 0 NOT NULL CHECK ("current" IN (0, 1)),
    summary_markdown CLOB              NOT NULL,
    sort_order       NUMBER(10)        DEFAULT 0 NOT NULL,
    created_at       TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at       TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE experience_highlights (
    experience_highlight_id VARCHAR2(36 CHAR) PRIMARY KEY,
    experience_id           VARCHAR2(36 CHAR) NOT NULL REFERENCES experiences(experience_id) ON DELETE CASCADE,
    body_markdown           CLOB              NOT NULL,
    sort_order              NUMBER(10)        DEFAULT 0 NOT NULL
);

CREATE TABLE projects (
    project_id           VARCHAR2(36 CHAR) PRIMARY KEY,
    slug                 VARCHAR2(500)   NOT NULL UNIQUE,
    title                VARCHAR2(500)   NOT NULL,
    tagline              CLOB,
    description_markdown CLOB            NOT NULL,
    cover_image_url      VARCHAR2(4000),
    repo_url             VARCHAR2(4000),
    demo_url             VARCHAR2(4000),
    tech_stack           VARCHAR2(4000)  DEFAULT '[]' NOT NULL CHECK (tech_stack IS JSON),
    status               VARCHAR2(20)    DEFAULT 'draft' NOT NULL CHECK (status IN ('draft', 'published')),
    featured             NUMBER(1)       DEFAULT 0 NOT NULL CHECK (featured IN (0, 1)),
    sort_order           NUMBER(10)      DEFAULT 0 NOT NULL,
    published_at         TIMESTAMP WITH TIME ZONE,
    created_at           TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at           TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE project_links (
    project_link_id VARCHAR2(36 CHAR) PRIMARY KEY,
    project_id      VARCHAR2(36 CHAR) NOT NULL REFERENCES projects(project_id) ON DELETE CASCADE,
    label           VARCHAR2(500),
    url             VARCHAR2(4000),
    kind            VARCHAR2(20)      NOT NULL CHECK (kind IN ('repo', 'demo', 'docs', 'other'))
);

CREATE TABLE blog_posts (
    blog_post_id    VARCHAR2(36 CHAR) PRIMARY KEY,
    slug            VARCHAR2(500)   NOT NULL UNIQUE,
    title           VARCHAR2(500)   NOT NULL,
    excerpt         CLOB,
    body_markdown   CLOB            NOT NULL,
    cover_image_url VARCHAR2(4000),
    status          VARCHAR2(20)    DEFAULT 'draft' NOT NULL CHECK (status IN ('draft', 'published')),
    view_count      NUMBER(10)      DEFAULT 0 NOT NULL,
    published_at    TIMESTAMP WITH TIME ZONE,
    created_at      TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at      TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- Postgres used a partial index (WHERE status = 'published'); Oracle has no equivalent,
-- so this is a plain index on published_at.
CREATE INDEX idx_blog_posts_published_at ON blog_posts (published_at DESC);

CREATE TABLE tags (
    tag_id VARCHAR2(36 CHAR) PRIMARY KEY,
    name   VARCHAR2(500) NOT NULL UNIQUE,
    slug   VARCHAR2(500) NOT NULL UNIQUE
);

CREATE TABLE post_tags (
    blog_post_id VARCHAR2(36 CHAR) NOT NULL REFERENCES blog_posts(blog_post_id) ON DELETE CASCADE,
    tag_id       VARCHAR2(36 CHAR) NOT NULL REFERENCES tags(tag_id) ON DELETE CASCADE,
    PRIMARY KEY (blog_post_id, tag_id)
);

CREATE TABLE assets (
    asset_id     VARCHAR2(36 CHAR) PRIMARY KEY,
    key          VARCHAR2(1000) NOT NULL UNIQUE,
    url          VARCHAR2(4000),
    content_type VARCHAR2(500),
    size_bytes   NUMBER(19),
    uploaded_at  TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE admin_users (
    admin_user_id VARCHAR2(36 CHAR) PRIMARY KEY,
    username      VARCHAR2(500) NOT NULL UNIQUE,
    password_hash VARCHAR2(100) NOT NULL,
    created_at    TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);
